=== navikt/k9-dokgen/content/templates/klage_avvist_arbeidsgiver/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles",
    "søkerFødselsdato"
  ],
  "properties": {
    "felles": {
      "type": "object"
    },
    "ytelse": {
      "type": "string"
    },
    "avdeling": {
      "type": "string"
    },
    "aarsakKlagetForSent": {
      "type": "boolean"
    },
    "aarsakManglerUnderskrift": {
      "type": "boolean"
    },
    "aarsakIkkeEtVedtak": {
      "type": "boolean"
    },
    "aarsakVedtakGjelderIkkePart": {
      "type": "boolean"
    },
    "aarsakManglerKlagegrunn": {
      "type": "boolean"
    },
    "hjemler": {
      "type": "string"
    },
    "søkerFødselsdato": {
      "type": "string"
    }
  }
}

=== navikt/k9-dokgen/content/templates/klage_avvist_arbeidsgiver/testdata/test.json
{
  "søkerFødselsdato": "30.02.1975",
  "felles": {
    "søkerNavn": "Selv Sjeler",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "1. mai 2020",
    "erVurdertAvNK": false,
    "mottaker": {
      "arbeidsgiver": true,
      "bruker": false,
      "navn": "Arbeidsgiver AS",
      "id": "123456789"
    }
  },
  "ytelse": "inntektkompensasjon for frilans og selvstendig næringsdrivende",
  "avdeling": "NAV",
  "aarsakKlagetForSent": true,
  "aarsakManglerUnderskrift": true,
  "aarsakIkkeEtVedtak": true,
  "aarsakVedtakGjelderIkkePart": true,
  "aarsakManglerKlagegrunn": true,
  "hjemler": "Vedtaket er gjort etter folketrygdloven § 21-12 og forvaltningsloven §§ 31 og 34."
}
