=== navikt/k9-dokgen/content/templates/klage/bruker/avvist/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles"
  ],
  "properties": {
    "felles": {
      "required": [
        "mottaker",
        "brevDato",
        "fritekst",
        "erVurdertAvNK"
      ],
      "properties": {
        "søkerNavn": {
          "type": "string"
        },
        "søkerId": {
          "type": "string"
        },
        "mottaker": {
          "required": [
            "navn",
            "id",
            "bruker"
          ],
          "properties": {
            "arbeidsgiver": {
              "type": "boolean"
            },
            "bruker": {
              "type": "boolean"
            },
            "navn": {
              "type": "string"
            },
            "id": {
              "type": "string"
            }
          }
        },

        "brevDato": {
          "type": "string"
        },
        "fritekst": {
          "type": "string"
        },
        "erVurdertAvNK": {
          "type": "boolean"
        }
      }
    },
    "ytelse": {
      "type": "string"
    },
    "avdeling": {
      "type": "string"
    },
    "flereÅrsaker": {
      "type": "boolean"
    },
    "aarsakKlagetForSent": {
      "type": "boolean"
    },
    "aarsakManglerUnderskrift": {
      "type": "boolean"
    },
    "aarsakIkkeEtVedtak": {
      "type": "boolean"
    },
    "aarsakVedtakGjelderIkkePart": {
      "type": "boolean"
    },
    "aarsakManglerKlagegrunn": {
      "type": "boolean"
    },
    "hjemler": {
      "type": "string"
    }
  }
}

=== navikt/k9-dokgen/content/templates/klage/bruker/avvist/testdata/test.json
{
  "felles": {
    "hovedytelse": "OMSORGSPENGER",
    "brevnavn": "omsorgspenger",
    "brevDato": "1. mai 2020",
    "erVurdertAvNK": false,
    "mottaker": {
      "arbeidsgiver": false,
      "bruker": true,
      "navn": "Selv Sjeler",
      "id": "300220 12345"
    },
    "fritekst": "Vi mener at du forklart med denne friteksten har fått medhold"
  },
  "ytelse": "omsorgspenger",
  "avdeling": "NAV",
  "flereÅrsaker": true,
  "aarsakKlagetForSent": true,
  "aarsakManglerUnderskrift": true,
  "aarsakIkkeEtVedtak": true,
  "aarsakVedtakGjelderIkkePart": true,
  "aarsakManglerKlagegrunn": true,
  "hjemler": "Vedtaket er gjort etter folketrygdloven § 21-12 og forvaltningsloven §§ 31 og 34."
}
