=== navikt/k9-dokgen/content/templates/klage_avvist/schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "felles"
  ],
  "properties": {
    "felles": {
      "type": "object"
    },
    "ytelse": {
      "type": "string"
    },
    "avdeling": {
      "type": "string"
    },
    "flere√Örsaker": {
      "type": "boolean"
    },
    "aarsakKlagetForSent": {
      "type": "boolean"
    },
    "aarsakManglerUnderskrift": {
      "type": "boolean"
    },
    "aarsakIkkeEtVedtak": {
      "type": "boolean"
    },
    "aarsakVedtakGjelderIkkePart": {
      "type": "boolean"
    },
    "aarsakManglerKlagegrunn": {
      "type": "boolean"
    },
    "hjemler": {
      "type": "string"
    }
  }
}

=== navikt/k9-dokgen/content/templates/klage_avvist/testdata/test.json
{
  "felles": {
    "søkerNavn": "Selv Sjeler",
    "søkerPersonnummer": "300220 12345",
    "brevDato": "1. mai 2020"
  },
  "ytelse": "inntektkompensasjon for frilans og selvstendig næringsdrivende",
  "avdeling": "NAV",
  "aarsakKlagetForSent": true,
  "aarsakManglerUnderskrift": true,
  "aarsakIkkeEtVedtak": true,
  "aarsakVedtakGjelderIkkePart": true,
  "aarsakManglerKlagegrunn": true
}
